version: '3'
services:
  spybot:
    build: .
    env_file: 
      - .env
    volumes:
     - ./speedrunners.db:/app/speedrunners.db
     - ./.env:/app/.env
     - ./credentials.json:/app/credentials.json
    command: python -u spyBot.py


